name: Auto Scrape WaterLevel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'  # เวลาไทย 20:00

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev
          npm install puppeteer json2csv dayjs

      - name: Run Puppeteer scraper
        run: node scrap2.js

      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./waterlevel_report.csv
          name: waterlevel_report.csv
          folderId: ${{ secrets.PURIPAT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
          encoded: false
