name: Auto Scrape Dam (Large & Medium)

on:
  workflow_dispatch: {}
  schedule:
    # 20:00 Asia/Bangkok = 13:00 UTC
    - cron: "0 13 * * *"

permissions:
  contents: write  # สำหรับ commit ผลลัพธ์กลับเข้า repo

concurrency:
  group: scrape-dam
  cancel-in-progress: false

env:
  TZ: Asia/Bangkok
  PYTHONUTF8: "1"

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Show Chrome version
        run: |
          google-chrome --version || true
          which google-chrome || true

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas

      - name: Run scraper (with basic retry)
        shell: bash
        run: |
          set -e
          echo "Start scrape at $(date)"
          for i in 1 2 3; do
            echo "Attempt #$i"
            if python scrap3.py; then
              echo "Scrape success"
              break
            fi
            echo "Sleep before retry..."
            sleep 20
            if [ "$i" = "3" ]; then
              echo "All attempts failed."
              exit 1
            fi
          done

      - name: List outputs
        run: |
          ls -al
          echo "Preview CSV heads:"
          for f in waterdam_report_large.csv waterdam_report_medium.csv; do
            if [ -f "$f" ]; then
              echo "== $f =="
              head -n 5 "$f"
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dam-csv-${{ github.run_id }}
          path: |
            waterdam_report_large.csv
            waterdam_report_medium.csv
          if-no-files-found: warn
          retention-days: 7

      - name: Commit CSVs back to repo (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add waterdam_report_large.csv waterdam_report_medium.csv || true
          if ! git diff --cached --quiet; then
            git commit -m "Update dam CSVs: $(date +'%Y-%m-%d %H:%M %Z')"
            git push
          else
            echo "No changes to commit."
          fi
