name: Combine & Upload Dam CSV

on:
  workflow_dispatch:
  schedule:
    # 20:10 Asia/Bangkok = 13:10 UTC
    - cron: "10 13 * * *"

permissions:
  contents: read

jobs:
  combine-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TZ: Asia/Bangkok

      # --- ชื่อไฟล์อินพุต/เอาต์พุต ---
      CSV_LARGE: waterdam_report_large.csv
      CSV_MEDIUM: waterdam_report_medium.csv
      CSV_OUT: waterdam_report.csv

      # --- อัปโหลดไป Google Drive ---
      ENABLE_GOOGLE_DRIVE_UPLOAD: "true"                   # ตั้ง "false" หากยังไม่อยากอัปโหลด
      DRIVE_FOLDER_ID: ${{ secrets.PURIPAT_ID }}           # <- ใส่ใน Secrets
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT }} # <- ใส่ใน Secrets (เนื้อหา JSON ทั้งไฟล์)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Google Chrome (for Selenium in scrap3.py)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Python packages (inline)
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas google-api-python-client google-auth google-auth-httplib2

      # ✅ แก้แล้ว: เช็ก Secrets ผ่าน env (ไม่พังจาก JSON หลายบรรทัด)
      - name: Sanity check Drive secrets
        env:
          ENABLE_GOOGLE_DRIVE_UPLOAD: ${{ env.ENABLE_GOOGLE_DRIVE_UPLOAD }}
          DRIVE_FOLDER_ID: ${{ secrets.PURIPAT_ID }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT }}
        run: |
          set -euo pipefail
          if [ "${ENABLE_GOOGLE_DRIVE_UPLOAD}" = "true" ]; then
            if [ -z "${DRIVE_FOLDER_ID:-}" ]; then
              echo "❌ Missing secret PURIPAT_ID"; exit 1
            fi
            if [ -z "${SERVICE_ACCOUNT_JSON:-}" ]; then
              echo "❌ Missing secret SERVICE_ACCOUNT"; exit 1
            fi
            echo "✅ Secrets OK"
          else
            echo "ℹ️ ENABLE_GOOGLE_DRIVE_UPLOAD=false -> skip Drive upload"
          fi

      # ---------- 1) รัน scraper สร้างไฟล์อินพุต ----------
      - name: Run scrap3.py (generate CSVs, retry up to 3)
        shell: bash
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt #$i at $(date)"
            if python scrap3.py; then
              echo "Scrape success"
              break
            fi
            echo "Sleep before retry..."
            sleep 20
            if [ "$i" = "3" ]; then
              echo "All attempts failed."
              exit 1
            fi
          done

      - name: Preview CSV heads (inputs)
        run: |
          for f in "${{ env.CSV_LARGE }}" "${{ env.CSV_MEDIUM }}"; do
            if [ -f "$f" ]; then
              echo "== $f =="; head -n 5 "$f"
            else
              echo "!! Missing $f"; exit 1
            fi
          done

      # ---------- 2) รวม + อัปโหลด ----------
      - name: Run Combine Script (scrap4.py)
        run: |
          python scrap4.py

      - name: Show Output Head/Tail
        if: always()
        run: |
          echo "----- HEAD -----"; head -n 5 "${CSV_OUT}" || true
          echo "----- TAIL -----"; tail -n 5 "${CSV_OUT}" || true
          echo "----- WC -----"; wc -l "${CSV_OUT}" || true
