name: Auto Scrape WaterLevel 

on:
  schedule:
    - cron: '0 13 * * *'  # รันทุกวันเวลา 20:00 ตามเวลาไทย (UTC+7)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium pandas

      - name: Set environment variables for Chrome
        run: |
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run scraper
        run: python scrap2.py

      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./waterlevel_report.csv
          name: waterlevel_report.csv
          folderId: ${{ secrets.PURIPAT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
          encoded: false
