name: Scrape Water Dam Data

on:
  schedule:
    # รันทุกวันเวลา 20:00 ไทย (UTC+7) = 13:00 UTC
    - cron: "0 13 * * *"
  workflow_dispatch:  # รันด้วยมือได้

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install selenium pandas

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Run scraper
        run: python scrape_dam.py

      - name: Commit & Push CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add waterdam_report_*.csv
          git commit -m "Update water dam data [skip ci]" || echo "No changes"
          git push
