name: Combine & Upload Dam CSV

on:
  workflow_dispatch:
  schedule:
    # 20:10 Asia/Bangkok = 13:10 UTC
    - cron: "10 13 * * *"

permissions:
  contents: read

jobs:
  combine-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Bangkok

      # ---- ชื่อไฟล์อินพุต/เอาต์พุต (ปรับได้) ----
      CSV_LARGE: waterdam_report_large.csv
      CSV_MEDIUM: waterdam_report_medium.csv
      CSV_OUT: waterdam_report.csv

      # ---- การอัปโหลด ----
      ENABLE_GOOGLE_DRIVE_UPLOAD: "true"   # ตั้ง "false" ถ้ายังไม่อยากอัปโหลด
      DRIVE_FOLDER_ID: ${{ secrets.PURIPAT_ID }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (ถ้ามีขั้นตอนดาวน์โหลดไฟล์อินพุตจาก artifact/ที่อื่น ให้เพิ่ม step ตรงนี้)

      - name: Run Combine Script
        run: |
          python combine_waterdam.py

      - name: Show Output Head/Tail
        if: always()
        run: |
          echo "----- HEAD -----"
          head -n 5 "${CSV_OUT}" || true
          echo "----- TAIL -----"
          tail -n 5 "${CSV_OUT}" || true

