name: Auto Scrape & Combine Dam CSV

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"   # 20:00 Asia/Bangkok

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      CSV_LARGE: waterdam_report_large.csv
      CSV_MEDIUM: waterdam_report_medium.csv
      CSV_OUT: waterdam_report.csv
      ENABLE_GOOGLE_DRIVE_UPLOAD: "true"
      DRIVE_FOLDER_ID: ${{ secrets.PURIPAT_ID }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas google-api-python-client google-auth google-auth-httplib2

      - name: Run scrap3.py
        run: python scrap3.py

      - name: Run scrap4.py
        run: python scrap4.py

      - name: Show combined head/tail
        if: always()
        run: |
          echo "----- HEAD -----"; head -n 5 "${CSV_OUT}" || true
          echo "----- TAIL -----"; tail -n 5 "${CSV_OUT}" || true
          wc -l "${CSV_OUT}" || true
