name: Combine & Upload Dam CSV (Only scrap4.py)

on:
  workflow_dispatch:
  schedule:
    # 20:30 Asia/Bangkok = 13:30 UTC
    - cron: "30 13 * * *"

permissions:
  contents: read

jobs:
  combine-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Bangkok

      # --- ชื่อไฟล์อินพุต/เอาต์พุต ---
      CSV_LARGE: waterdam_report_large.csv
      CSV_MEDIUM: waterdam_report_medium.csv
      CSV_OUT: waterdam_report.csv

      # --- ตั้งค่าอัปโหลดไป Google Drive ---
      ENABLE_GOOGLE_DRIVE_UPLOAD: "true"                   # ตั้ง "false" ถ้ายังไม่อยากอัปโหลด
      DRIVE_FOLDER_ID: ${{ secrets.PURIPAT_ID }}           # <- ใส่ใน Secrets
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT }} # <- ใส่ใน Secrets (JSON content)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas google-api-python-client google-auth google-auth-httplib2

      - name: Run scrap4.py (combine & upload)
        run: |
          python scrap4.py

      - name: Show Output Head/Tail
        if: always()
        run: |
          echo "----- HEAD -----"
          head -n 5 "${CSV_OUT}" || true
          echo "----- TAIL -----"
          tail -n 5 "${CSV_OUT}" || true
          echo "----- WC -----"
          wc -l "${CSV_OUT}" || true
