name: Auto Scrape Waterlevel

on:
  schedule:
    - cron: '0 13 * * *'  # เวลาไทย 20:00
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Playwright + Browsers
        run: |
          pip install playwright pandas gdown google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib
          playwright install

      - name: Run scraper script with Playwright
        run: python scrap2.py

      - name: Debug – List files
        run: ls -lah

      - name: Check if CSV exists before upload
        run: |
          if [ ! -f waterlevel_report.csv ]; then
            echo "❌ ไม่พบไฟล์ waterlevel_report.csv — ข้ามการอัปโหลด"
            exit 0
          fi

      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./waterlevel_report.csv
          name: waterlevel_report.csv
          folderId: ${{ secrets.PURIPAT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
          encoded: false
