name: Scrape Dam Water Data

on:
  schedule:
    - cron: '0 14 * * *'  # รันทุกวัน 20:00 (เวลาไทย)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl jq
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -O chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Python packages
        run: pip install selenium pandas gdown google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Run Dam Scraper
        run: python scrap3.py

      - name: Upload Large Dam Data
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./waterdam_report_large.csv
          name: waterdam_report_large.csv
          folderId: ${{ secrets.PURIPAT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
          encoded: false

      - name: Upload Medium Dam Data
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./waterdam_report_medium.csv
          name: waterdam_report_medium.csv
          folderId: ${{ secrets.PURIPAT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
          encoded: false
