name: Auto Scrape Waterlevel

on:
  schedule:
    - cron: '0 13 * * *'  # เวลาไทย 20:00
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright pandas
          playwright install

      - name: Run scraper script
        run: python scrap2.py

      - name: Debug – List files in workspace
        run: ls -lah

      - name: Check if CSV exists before upload
        run: |
          if [ ! -f waterlevel_report.csv ]; then
            echo "ไม่พบไฟล์ waterlevel_report.csv — ยกเลิกการอัปโหลด"
            exit 1
          fi

      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./waterlevel_report.csv
          name: waterlevel_report.csv
          folderId: ${{ secrets.PURIPAT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
          encoded: false
