name: Auto Scrape WaterLevel

on:
  schedule:
    # รันทุกวันเวลา 20:00 ประเทศไทย (UTC+7) => 13:00 UTC
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome & Chromedriver
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y wget unzip curl jq ca-certificates
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -qO chromedriver.zip "$DRIVER_URL"
          unzip -q chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          rm -rf chromedriver.zip chromedriver-linux64
          google-chrome --version
          chromedriver --version

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas gdown google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Run scraper
        run: |
          set -eux
          python scrap2.py

      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./waterlevel_report.csv
          name: waterlevel_report.csv
          folderId: ${{ secrets.PURIPAT_ID }}
          credentials: ${{ secrets.SERVICE_ACCOUNT }}
          encoded: 'false'
