name: Combine & Upload Dam CSV

on:
  workflow_dispatch:
  schedule:
    # 20:10 Asia/Bangkok = 13:10 UTC
    - cron: "10 13 * * *"

permissions:
  contents: read

jobs:
  combine-upload:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Bangkok

      # --- ชื่อไฟล์อินพุต/เอาต์พุต (ปรับได้) ---
      CSV_LARGE: waterdam_report_large.csv
      CSV_MEDIUM: waterdam_report_medium.csv
      CSV_OUT: waterdam_report.csv

      # --- ตั้งค่าอัปโหลดไป Google Drive ---
      ENABLE_GOOGLE_DRIVE_UPLOAD: "true"                # ตั้ง "false" หากยังไม่อยากอัปโหลด
      DRIVE_FOLDER_ID: ${{ secrets.PURIPAT_ID }}        # <- ใส่ใน Secrets
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT }}  # <- ใส่ใน Secrets

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python packages (inline)
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.2.2 \
                      google-api-python-client==2.141.0 \
                      google-auth==2.35.0 \
                      google-auth-httplib2==0.2.0

      # (ถ้าต้องการ: เพิ่ม step ดาวน์โหลด/คัดลอกไฟล์ CSV อินพุตก่อนรันที่นี่)

      - name: Run Combine Script
        run: |
          python scrap4.py

      - name: Show Output Head/Tail
        if: always()
        run: |
          echo "----- HEAD -----"
          head -n 5 "${CSV_OUT}" || true
          echo "----- TAIL -----"
          tail -n 5 "${CSV_OUT}" || true
