name: Auto Scrape WaterLevel

on:
  schedule:
    # รันทุกวัน 20:00 ไทย (UTC+7) = 13:00 UTC
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PYTHONUNBUFFERED: "1"
      CSV_OUT: waterlevel_report.csv

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ใช้ Chrome พร้อม Selenium Manager (ไม่ต้องลง chromedriver เอง)
      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Show Chrome version
        run: google-chrome --version || true

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas google-api-python-client google-auth google-auth-httplib2

      - name: Run scraper
        run: |
          set -eux
          python scrap2.py
          test -f "${CSV_OUT}"

      - name: Upload artifact (CSV)
        if: always() && hashFiles(env.CSV_OUT) != ''
        uses: actions/upload-artifact@v4
        with:
          name: waterlevel_report
          path: ${{ env.CSV_OUT }}
          if-no-files-found: ignore
          retention-days: 7

      # อัปโหลดแบบปลอดภัย:
      # - ถ้ามี DRIVE_FILE_ID -> Overwrite ไฟล์เดิม (My Drive/Shared Drive ก็ได้)
      # - ถ้าไม่มี แต่ PURIPAT_ID เป็น Shared Drive -> Create ใหม่ในโฟลเดอร์นั้น
      # - ถ้า PURIPAT_ID เป็น My Drive และไม่มีไฟล์เดิม -> แจ้งวิธีแก้ (ต้องสร้างไฟล์ว่างแล้วแชร์ให้ SA หรือใส่ DRIVE_FILE_ID)
      - name: Upload to Google Drive (smart update-or-create)
        if: success() && hashFiles('waterlevel_report.csv') != ''
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT }}   # JSON ของ Service Account (ทั้งก้อน)
          DRIVE_FILE_ID: ${{ secrets.DRIVE_FILE_ID }}            # (ทางเลือก 1) fileId ของไฟล์เดิมใน My Drive
          DRIVE_FOLDER_ID: ${{ secrets.PURIPAT_ID }}             # (ทางเลือก 2) โฟลเดอร์ปลายทาง (My/Shared Drive ใส่ได้)
          CSV_OUT: waterlevel_report.csv
        run: |
          python - <<'PY'
          import os, json, io, sys
          from google.oauth2.service_account import Credentials
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload, MediaIoBaseDownload
          from googleapiclient.errors import HttpError

          SA = json.loads(os.environ["SERVICE_ACCOUNT_JSON"])
          FILE_ID = (os.environ.get("DRIVE_FILE_ID") or "").strip() or None
          FOLDER_ID = (os.environ.get("DRIVE_FOLDER_ID") or "").strip() or None
          CSV = os.environ.get("CSV_OUT", "waterlevel_report.csv")

          creds = Credentials.from_service_account_info(SA, scopes=["https://www.googleapis.com/auth/drive"])
          drive = build("drive", "v3", credentials=creds, cache_discovery=False)

          def get_meta(fid):
              return drive.files().get(fileId=fid, fields="id,name,size,mimeType,driveId,parents", supportsAllDrives=True).execute()

          def overwrite(fid, path):
              media = MediaFileUpload(path, mimetype="text/csv", resumable=True)
              drive.files().update(fileId=fid, media_body=media, supportsAllDrives=True).execute()
              m = get_meta(fid)
              print(f"✅ Overwritten: id={m['id']} name={m['name']} size={m.get('size','?')} bytes")

          def create_in_folder(folder_id, path):
              meta = {"name": os.path.basename(path), "parents": [folder_id]}
              media = MediaFileUpload(path, mimetype="text/csv", resumable=True)
              newf = drive.files().create(body=meta, media_body=media, fields="id", supportsAllDrives=True).execute()
              m = get_meta(newf["id"])
              print(f"✅ Created: id={m['id']} name={m['name']} size={m.get('size','?')} bytes")

          def escape_single_quotes(s: str) -> str:
              return s.replace("'", "\\'")

          def find_by_name_in_folder(name, folder_id):
              safe_name = escape_single_quotes(name)
              q = "name = '{}' and '{}' in parents and trashed = false".format(safe_name, folder_id)
              r = drive.files().list(q=q, fields="files(id,name)", supportsAllDrives=True, includeItemsFromAllDrives=True).execute()
              files = r.get("files", [])
              return files[0]["id"] if files else None

          # 1) มี FILE_ID -> อัปเดตทับทันที (ใช้ได้ทั้ง My/Shared Drive; ต้องแชร์ให้ SA เป็น Editor)
          if FILE_ID:
              overwrite(FILE_ID, CSV)
              sys.exit(0)

          # 2) ต้องมี FOLDER_ID อย่างน้อย เพื่อไปต่อ
          if not FOLDER_ID:
              print("❌ ต้องใส่ DRIVE_FILE_ID (ไฟล์เดิมใน My Drive) หรือ PURIPAT_ID (โฟลเดอร์ใน Shared Drive)", file=sys.stderr)
              sys.exit(1)

          # เช็กว่า FOLDER_ID เป็น Shared Drive หรือ My Drive
          try:
              fmeta = get_meta(FOLDER_ID)
          except HttpError as e:
              print(f"❌ อ่านโฟลเดอร์ไม่สำเร็จ: {e}", file=sys.stderr); sys.exit(1)
          is_shared_drive = bool(fmeta.get("driveId"))

          # 3) ถ้ามีไฟล์ชื่อนี้อยู่แล้วในโฟลเดอร์ -> overwrite (ไม่ต้องสร้างใหม่)
          name = os.path.basename(CSV)
          existing_id = find_by_name_in_folder(name, FOLDER_ID)
          if existing_id:
              print("[INFO] พบไฟล์เดิมในโฟลเดอร์ -> overwrite")
              overwrite(existing_id, CSV)
              sys.exit(0)

          # 4) ไม่มีไฟล์เดิม:
          if is_shared_drive:
              # Shared Drive: SA มีโควตารวม -> สร้างใหม่ได้
              create_in_folder(FOLDER_ID, CSV)
              sys.exit(0)
          else:
              # My Drive: SA ไม่มีโควตาสร้างใหม่ -> บอกวิธีแก้
              print("❌ PURIPAT_ID เป็นโฟลเดอร์ใน My Drive และไม่พบไฟล์เดิมให้เขียนทับ", file=sys.stderr)
              print("👉 ทางเลือก:", file=sys.stderr)
              print("   (A) สร้างไฟล์ว่างชื่อเดียวกันในโฟลเดอร์นั้น แล้วแชร์ให้ SA เป็น Editor จากนั้นรันใหม่ (สคริปต์จะ overwrite ให้)", file=sys.stderr)
              print("   (B) เติม SECRET ชื่อ DRIVE_FILE_ID เป็น fileId ของไฟล์เดิม เพื่ออัปเดตทับตรง ๆ", file=sys.stderr)
              print("   (C) ย้ายไป Shared Drive และใช้ PURIPAT_ID ของ Shared Drive แทน", file=sys.stderr)
              sys.exit(1)
          PY
